id = "soma"
name = "Soma"
version = "0.6.0"
schema_version = 1
authors = ["Gabriel <gabriel@minatel.dev>"]
description = "Syntax highlighting and LSP support for the Soma programming language."
repository = "https://github.com/srgaabriel/soma"

[grammars.soma]
repository = "https://github.com/srgaabriel/tree-sitter-soma"
rev = "a8d622c97f9bb629ddf9a6a197e65013fa56ce4c"

[language_servers.souls]
name = "SouLS (Soma Language Server)"
language = "Soma"