id = "soma"
name = "Soma"
version = "0.4.0"
schema_version = 1
authors = ["Gabriel <gabriel@minatel.dev>"]
description = "Syntax highlighting and LSP support for the Soma programming language."
repository = "https://github.com/srgaabriel/soma"

[grammars.soma]
repository = "https://github.com/srgaabriel/tree-sitter-soma"
rev = "e8979df833eec37cb440c791918836dab7308354"

[language_servers.soma]
name = "SouLS (Soma Language Server)"
language = "Soma"